(function(){'use strict';const $=id=>document.getElementById(id),esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let rows=[];
const token=()=>sessionStorage.getItem('ps_admin_token')||'';
async function api(path,opts={}){const r=await fetch('/api'+path,{method:opts.method||'GET',headers:{Authorization:'Bearer '+token(),'Content-Type':'application/json'},body:opts.body?JSON.stringify(opts.body):undefined});const d=r.status===204?null:await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error||'Request failed ('+r.status+')');return d}
function toast(msg,bad=false){const t=$('toast');if(!t)return;t.textContent=msg;t.classList.remove('hidden','bad');if(bad)t.classList.add('bad');setTimeout(()=>t.classList.add('hidden'),3500)}
function clear(){['phStudioId','phStudioName','phStudioWebsite','phStudioLogo'].forEach(id=>$(id).value='');$('phStudioFile').value='';$('phStudioPreviewWrap').textContent='Select a logo to preview it before saving.'}
function render(){const q=($('phStudioSearch').value||'').toLowerCase();const list=rows.filter(x=>(x.name+' '+x.website_url).toLowerCase().includes(q));$('phStudioTable').innerHTML=list.length?'<div class="tableWrap"><table><thead><tr><th>STUDIO</th><th>WEBSITE</th><th>LINKED TITLES</th><th>ACTIONS</th></tr></thead><tbody>'+list.map(x=>'<tr><td><div class="itemCell">'+(x.logo_url?'<img class="poster" src="'+esc(x.logo_url)+'" alt="" onerror="this.hidden=true">':'<div class="poster"></div>')+'<div><div class="itemTitle">'+esc(x.name)+'</div><div class="subline">'+esc(x.slug)+'</div></div></div></td><td>'+(x.website_url?'<a href="'+esc(x.website_url)+'" target="_blank" rel="noopener noreferrer">'+esc(x.website_url)+'</a>':'—')+'</td><td>'+Number(x.anime_count||0)+'</td><td><div class="rowActions"><button class="btn secondary small" data-edit="'+x.id+'">Edit</button></div></td></tr>').join('')+'</tbody></table></div>':'<div class="empty">No studios found.</div>'}
async function load(){if(!token())return;try{rows=await api('/admin/studios');render()}catch(e){toast(e.message,true)}}
$('phStudioFile')?.addEventListener('change',()=>{const f=$('phStudioFile').files?.[0];if(!f)return;if(!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>2*1024*1024){toast('Use PNG, JPEG or WebP under 2 MB.',true);$('phStudioFile').value='';return}const reader=new FileReader();reader.onload=()=>{$('phStudioLogo').value=String(reader.result);$('phStudioPreviewWrap').innerHTML='<img alt="Studio logo preview" src="'+esc(reader.result)+'" style="width:100px;height:100px;object-fit:contain;background:#0b101a;border:1px solid var(--line);border-radius:10px;padding:8px">';};reader.readAsDataURL(f)});
$('phStudioForm')?.addEventListener('submit',async e=>{e.preventDefault();const btn=e.currentTarget.querySelector('button[type=submit]');btn.disabled=true;try{const id=$('phStudioId').value;const body={name:$('phStudioName').value.trim(),websiteUrl:$('phStudioWebsite').value.trim(),logoUrl:$('phStudioLogo').value.trim()};if(!body.name)throw new Error('Studio name is required.');if(body.websiteUrl&&!/^https?:\/\//i.test(body.websiteUrl))throw new Error('Website URL must start with http:// or https://');await api('/admin/studios'+(id?'/'+id:''),{method:id?'PUT':'POST',body});clear();await load();toast(id?'Studio updated':'Studio added')}catch(e){toast(e.message,true)}finally{btn.disabled=false}});
$('phStudioCancel')?.addEventListener('click',clear);$('phStudioRefresh')?.addEventListener('click',load);$('phStudioSearch')?.addEventListener('input',render);
$('phStudioTable')?.addEventListener('click',e=>{const b=e.target.closest('[data-edit]');if(!b)return;const x=rows.find(y=>String(y.id)===b.dataset.edit);if(!x)return;$('phStudioId').value=x.id;$('phStudioName').value=x.name||'';$('phStudioWebsite').value=x.website_url||'';$('phStudioLogo').value=x.logo_url||'';$('phStudioPreviewWrap').innerHTML=x.logo_url?'<img alt="Studio logo preview" src="'+esc(x.logo_url)+'" style="width:100px;height:100px;object-fit:contain;background:#0b101a;border:1px solid var(--line);border-radius:10px;padding:8px">':'No logo uploaded.';window.scrollTo({top:0,behavior:'smooth'})});
document.addEventListener('click',e=>{if(e.target.closest('[data-tab="studios"]'))setTimeout(load,100)});document.addEventListener('DOMContentLoaded',()=>{setTimeout(()=>{if($('view-studios')&&!$('view-studios').classList.contains('hidden'))load()},500)});
})();