import { useState } from "react";
import { ActivityIndicator, Pressable, SafeAreaView, StyleSheet, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import { api, setSession } from "../src/api";
export default function Login(){
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function submit(){setBusy(true);setError("");try{const d=await api.login(email.trim(),password);const token=d.token||d.accessToken||d.session||"";if(token)await setSession(token);router.replace("/")}catch(e:any){setError(e?.message||"Login failed")}finally{setBusy(false)}}
 return <SafeAreaView style={s.safe}><View style={s.box}><Text style={s.brand}>PRIME HINDI</Text><Text style={s.heading}>Welcome back</Text><Text style={s.muted}>Sign in to continue watching.</Text><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="Email" placeholderTextColor="#70798c" style={s.input}/><TextInput value={password} onChangeText={setPassword} secureTextEntry placeholder="Password" placeholderTextColor="#70798c" style={s.input}/>{error?<Text style={s.error}>{error}</Text>:null}<Pressable disabled={busy} onPress={submit} style={s.button}>{busy?<ActivityIndicator color="#fff"/>:<Text style={s.buttonText}>SIGN IN</Text>}</Pressable><Pressable onPress={()=>router.replace("/")}><Text style={s.back}>← Back to Prime Hindi</Text></Pressable></View></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#0A0D14"},box:{margin:"auto",width:"88%",padding:24,backgroundColor:"#111622",borderRadius:20,borderWidth:1,borderColor:"#1E2536"},brand:{color:"#2F6BFF",fontWeight:"900",fontSize:18},heading:{color:"#F2F5FA",fontSize:28,fontWeight:"900",marginTop:20},muted:{color:"#8A94A8",marginTop:5,marginBottom:22},input:{backgroundColor:"#0A0D14",borderWidth:1,borderColor:"#1E2536",borderRadius:12,color:"#fff",padding:13,marginBottom:12},button:{backgroundColor:"#2F6BFF",borderRadius:12,padding:14,alignItems:"center"},buttonText:{color:"#fff",fontWeight:"900"},error:{color:"#ff7b8a",marginBottom:10},back:{color:"#8A94A8",textAlign:"center",marginTop:18}});
