import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import pg from 'pg';
const {Pool}=pg; const app=express();
app.use(cors({origin:true,credentials:true})); app.use(express.json({limit:'2mb'}));
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_SSL==='true'?{rejectUnauthorized:false}:false});
const JWT_SECRET=process.env.JWT_SECRET||'change-me';
async function init(){await pool.query(`
CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,display_name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'user',created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS anime(id SERIAL PRIMARY KEY,title TEXT NOT NULL,slug TEXT UNIQUE NOT NULL,description TEXT DEFAULT '',poster_url TEXT DEFAULT '',banner_url TEXT DEFAULT '',year INT,genres TEXT[] DEFAULT '{}',rating NUMERIC(3,1),type TEXT DEFAULT 'series',status TEXT DEFAULT 'ongoing',hindi_dub BOOLEAN DEFAULT false,subtitles BOOLEAN DEFAULT true,is_exclusive BOOLEAN DEFAULT false,created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS episodes(id SERIAL PRIMARY KEY,anime_id INT REFERENCES anime(id) ON DELETE CASCADE,episode_number INT NOT NULL,title TEXT DEFAULT '',video_url TEXT NOT NULL,thumbnail_url TEXT DEFAULT '',is_exclusive BOOLEAN DEFAULT false,created_at TIMESTAMPTZ DEFAULT now());
ALTER TABLE episodes ADD COLUMN IF NOT EXISTS is_exclusive BOOLEAN DEFAULT false;
CREATE TABLE IF NOT EXISTS watchlist(user_id INT REFERENCES users(id) ON DELETE CASCADE,anime_id INT REFERENCES anime(id) ON DELETE CASCADE,PRIMARY KEY(user_id,anime_id));
CREATE TABLE IF NOT EXISTS progress(user_id INT REFERENCES users(id) ON DELETE CASCADE,episode_id INT REFERENCES episodes(id) ON DELETE CASCADE,seconds INT DEFAULT 0,updated_at TIMESTAMPTZ DEFAULT now(),PRIMARY KEY(user_id,episode_id));
CREATE TABLE IF NOT EXISTS branding(id INT PRIMARY KEY DEFAULT 1,logo_url TEXT DEFAULT '',updated_at TIMESTAMPTZ DEFAULT now());
INSERT INTO branding(id,logo_url) VALUES(1,'/assets/logo.jpg') ON CONFLICT(id) DO NOTHING;`);
if(process.env.ADMIN_EMAIL&&process.env.ADMIN_PASSWORD){const h=await bcrypt.hash(process.env.ADMIN_PASSWORD,12);await pool.query('insert into users(display_name,email,password_hash,role) values($1,$2,$3,$4) on conflict(email) do update set role=$4',['PDI Admin',process.env.ADMIN_EMAIL.toLowerCase(),h,'admin'])}}
function token(u){return jwt.sign({id:u.id,role:u.role},JWT_SECRET,{expiresIn:'7d'})}
function auth(req,res,next){try{req.user=jwt.verify((req.headers.authorization||'').replace(/^Bearer /,''),JWT_SECRET);next()}catch{return res.status(401).json({error:'Unauthorized'})}}
function admin(req,res,next){return auth(req,res,()=>req.user.role==='admin'?next():res.status(403).json({error:'Admin only'}))}
app.get('/api/health',async(req,res)=>{try{await pool.query('select 1');res.json({ok:true})}catch{res.status(503).json({ok:false})}});
app.post('/api/auth/register',async(req,res)=>{const{displayName,email,password}=req.body;if(!displayName||!email||!password)return res.status(400).json({error:'Missing fields'});try{const h=await bcrypt.hash(password,12);const{rows}=await pool.query('insert into users(display_name,email,password_hash) values($1,$2,$3) returning id,display_name,email,role,created_at',[displayName,email.toLowerCase(),h]);res.status(201).json({token:token(rows[0]),user:rows[0]})}catch{res.status(409).json({error:'Email already registered'})}});
app.post('/api/auth/login',async(req,res)=>{const{email,password,mfaCode}=req.body;const{rows}=await pool.query('select * from users where email=$1',[String(email||'').toLowerCase()]);if(!rows[0]||!(await bcrypt.compare(password||'',rows[0].password_hash)))return res.status(401).json({error:'Invalid credentials'});if(rows[0].role==='admin'&&process.env.ADMIN_MFA_CODE&&String(mfaCode||'')!==String(process.env.ADMIN_MFA_CODE))return res.status(401).json({error:'Invalid MFA / Security Passcode'});const u=rows[0];delete u.password_hash;res.json({token:token(u),user:u})});
app.get('/api/me',auth,async(req,res)=>{const{rows}=await pool.query('select id,display_name,email,role,created_at from users where id=$1',[req.user.id]);res.json(rows[0])});
app.get('/api/anime',async(req,res)=>{const{rows}=await pool.query('select * from anime order by is_exclusive desc,created_at desc');res.json(rows)});
app.get('/api/anime/:slug',async(req,res)=>{const a=(await pool.query('select * from anime where slug=$1',[req.params.slug])).rows[0];if(!a)return res.sendStatus(404);a.episodes=(await pool.query('select * from episodes where anime_id=$1 order by episode_number',[a.id])).rows;res.json(a)});
app.get('/api/branding',async(req,res)=>{const{rows}=await pool.query('select logo_url from branding where id=1');res.json({logoUrl:rows[0]?.logo_url||'/assets/logo.jpg'})});
app.get('/api/admin/users',admin,async(req,res)=>{const q=String(req.query.q||'').trim();const{rows}=await pool.query(`select id,display_name,email,role,created_at from users ${q?'where display_name ilike $1 or email ilike $1':''} order by created_at desc`,q?[`%${q}%`]:[]);res.json(rows)});
app.get('/api/admin/users/:id',admin,async(req,res)=>{const{rows}=await pool.query('select id,display_name,email,role,created_at from users where id=$1',[req.params.id]);if(!rows[0])return res.sendStatus(404);res.json(rows[0])});
app.get('/api/admin/users.csv',admin,async(req,res)=>{const{rows}=await pool.query('select id,display_name,email,role,created_at from users order by created_at desc');res.type('text/csv').send('id,display_name,email,role,created_at\\n'+rows.map(r=>[r.id,r.display_name,r.email,r.role,r.created_at.toISOString()].map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\\n'))});
app.put('/api/admin/branding',admin,async(req,res)=>{const logoUrl=String(req.body.logoUrl||'');if(!logoUrl)return res.status(400).json({error:'logoUrl required'});await pool.query('update branding set logo_url=$1,updated_at=now() where id=1',[logoUrl]);res.json({logoUrl})});
app.post('/api/admin/anime',admin,async(req,res)=>{const x=req.body;const{rows}=await pool.query('insert into anime(title,slug,description,poster_url,banner_url,year,genres,rating,type,status,hindi_dub,subtitles,is_exclusive) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) returning *',[x.title,x.slug,x.description||'',x.posterUrl||'',x.bannerUrl||'',x.year||null,x.genres||[],x.rating||null,x.type||'series',x.status||'ongoing',!!x.hindiDub,x.subtitles!==false,!!x.isExclusive]);res.status(201).json(rows[0])});
app.put('/api/admin/anime/:id',admin,async(req,res)=>{const x=req.body;const{rows}=await pool.query('update anime set title=$1,slug=$2,description=$3,poster_url=$4,banner_url=$5,year=$6,genres=$7,rating=$8,type=$9,status=$10,hindi_dub=$11,subtitles=$12,is_exclusive=$13 where id=$14 returning *',[x.title,x.slug,x.description||'',x.posterUrl||'',x.bannerUrl||'',x.year||null,x.genres||[],x.rating||null,x.type||'series',x.status||'ongoing',!!x.hindiDub,x.subtitles!==false,!!x.isExclusive,req.params.id]);if(!rows[0])return res.sendStatus(404);res.json(rows[0])});
app.delete('/api/admin/anime/:id',admin,async(req,res)=>{await pool.query('delete from anime where id=$1',[req.params.id]);res.sendStatus(204)});
app.get('/api/admin/episodes',admin,async(req,res)=>{const{rows}=await pool.query('select e.*,a.title anime_title from episodes e join anime a on a.id=e.anime_id order by a.title,e.episode_number');res.json(rows)});
app.post('/api/admin/episodes',admin,async(req,res)=>{const x=req.body;const{rows}=await pool.query('insert into episodes(anime_id,episode_number,title,video_url,thumbnail_url,is_exclusive) values($1,$2,$3,$4,$5,$6) returning *',[x.animeId,x.episodeNumber,x.title||'',x.videoUrl,x.thumbnailUrl||'',!!x.isExclusive]);res.status(201).json(rows[0])});
app.put('/api/admin/episodes/:id',admin,async(req,res)=>{const x=req.body;const{rows}=await pool.query('update episodes set anime_id=$1,episode_number=$2,title=$3,video_url=$4,thumbnail_url=$5,is_exclusive=$6 where id=$7 returning *',[x.animeId,x.episodeNumber,x.title||'',x.videoUrl,x.thumbnailUrl||'',!!x.isExclusive,req.params.id]);if(!rows[0])return res.sendStatus(404);res.json(rows[0])});
app.delete('/api/admin/episodes/:id',admin,async(req,res)=>{await pool.query('delete from episodes where id=$1',[req.params.id]);res.sendStatus(204)});
app.get('/api/watchlist',auth,async(req,res)=>{const{rows}=await pool.query('select a.* from watchlist w join anime a on a.id=w.anime_id where w.user_id=$1 order by a.title',[req.user.id]);res.json(rows)});
app.post('/api/watchlist/:animeId',auth,async(req,res)=>{await pool.query('insert into watchlist(user_id,anime_id) values($1,$2) on conflict do nothing',[req.user.id,req.params.animeId]);res.sendStatus(204)});
app.delete('/api/watchlist/:animeId',auth,async(req,res)=>{await pool.query('delete from watchlist where user_id=$1 and anime_id=$2',[req.user.id,req.params.animeId]);res.sendStatus(204)});
app.get('/api/progress',auth,async(req,res)=>{const{rows}=await pool.query('select * from progress where user_id=$1',[req.user.id]);res.json(rows)});
app.put('/api/progress/:episodeId',auth,async(req,res)=>{const seconds=Math.max(0,Number(req.body.seconds)||0);const{rows}=await pool.query('insert into progress(user_id,episode_id,seconds) values($1,$2,$3) on conflict(user_id,episode_id) do update set seconds=$3,updated_at=now() returning *',[req.user.id,req.params.episodeId,seconds]);res.json(rows[0])});
init().then(()=>app.listen(process.env.PORT||3000,'0.0.0.0')).catch(e=>{console.error(e);process.exit(1)});