import express from 'express';
import cors from 'cors';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import pg from 'pg';
import crypto from 'node:crypto';
import nodemailer from 'nodemailer';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
const {Pool}=pg; const app=express();
const allowedOrigins = new Set(
  (process.env.FRONTEND_URL || 'https://primordialstreams.up.railway.app')
    .split(',').map((value) => value.trim()).filter(Boolean)
);
allowedOrigins.add('https://primordialstreams.up.railway.app');
app.disable('x-powered-by');
app.set('trust proxy', 1);
app.use(helmet({ crossOriginResourcePolicy: { policy: 'cross-origin' } }));
app.use(cors({
  origin(origin, callback) {
    if (!origin || allowedOrigins.has(origin)) return callback(null, true);
    return callback(new Error('Origin not allowed by CORS'));
  },
  methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'],
  allowedHeaders: ['Content-Type', 'Authorization'],
  credentials: false,
  maxAge: 600
}));
app.use(express.json({limit:'8mb', strict:true}));
const apiLimiter = rateLimit({
  windowMs: 15 * 60 * 1000, limit: 600, standardHeaders: 'draft-8', legacyHeaders: false,
  message: { error: 'Too many requests. Please try again later.' }
});
const authLimiter = rateLimit({
  windowMs: 15 * 60 * 1000, limit: 20, standardHeaders: 'draft-8', legacyHeaders: false,
  message: { error: 'Too many authentication attempts. Please try again in 15 minutes.' }
});
app.use('/api', apiLimiter);
app.use(['/api/auth/login', '/api/auth/register', '/api/auth/google'], authLimiter);
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_SSL==='true'?{rejectUnauthorized:false}:false});
const JWT_SECRET=process.env.JWT_SECRET;
if (!JWT_SECRET || JWT_SECRET.length < 32 || JWT_SECRET === 'change-me') {
  throw new Error('JWT_SECRET must be configured with a random secret of at least 32 characters.');
}
async function init(){await pool.query(`
CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,display_name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'user',created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS anime(id SERIAL PRIMARY KEY,title TEXT NOT NULL,alt_title TEXT DEFAULT '',slug TEXT UNIQUE NOT NULL,description TEXT DEFAULT '',poster_url TEXT DEFAULT '',banner_url TEXT DEFAULT '',year INT,genres TEXT[] DEFAULT '{}',rating NUMERIC(3,1),type TEXT DEFAULT 'series',status TEXT DEFAULT 'ongoing',hindi_dub BOOLEAN DEFAULT false,subtitles BOOLEAN DEFAULT true,is_exclusive BOOLEAN DEFAULT false,characters JSONB DEFAULT '[]'::jsonb,created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS episodes(id SERIAL PRIMARY KEY,anime_id INT REFERENCES anime(id) ON DELETE CASCADE,season_number INT NOT NULL DEFAULT 1,episode_number INT NOT NULL,title TEXT DEFAULT '',video_url TEXT NOT NULL,thumbnail_url TEXT DEFAULT '',is_exclusive BOOLEAN DEFAULT false,created_at TIMESTAMPTZ DEFAULT now());
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url TEXT DEFAULT '';
ALTER TABLE episodes ADD COLUMN IF NOT EXISTS is_exclusive BOOLEAN DEFAULT false;
ALTER TABLE episodes ADD COLUMN IF NOT EXISTS season_number INT NOT NULL DEFAULT 1;
ALTER TABLE anime ADD COLUMN IF NOT EXISTS characters JSONB DEFAULT '[]'::jsonb;
ALTER TABLE anime ADD COLUMN IF NOT EXISTS voice_cast JSONB NOT NULL DEFAULT '[]'::jsonb;
UPDATE anime SET voice_cast=characters WHERE voice_cast='[]'::jsonb AND jsonb_typeof(characters)='array' AND characters <> '[]'::jsonb;
ALTER TABLE anime ADD COLUMN IF NOT EXISTS alt_title TEXT DEFAULT '';
CREATE TABLE IF NOT EXISTS watchlist(user_id INT REFERENCES users(id) ON DELETE CASCADE,anime_id INT REFERENCES anime(id) ON DELETE CASCADE,PRIMARY KEY(user_id,anime_id));
CREATE TABLE IF NOT EXISTS progress(user_id INT REFERENCES users(id) ON DELETE CASCADE,episode_id INT REFERENCES episodes(id) ON DELETE CASCADE,seconds INT DEFAULT 0,updated_at TIMESTAMPTZ DEFAULT now(),PRIMARY KEY(user_id,episode_id));
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_banned BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE anime ADD COLUMN IF NOT EXISTS is_published BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE anime ADD COLUMN IF NOT EXISTS is_featured BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE anime ADD COLUMN IF NOT EXISTS featured_order INT NOT NULL DEFAULT 0;
ALTER TABLE episodes ADD COLUMN IF NOT EXISTS is_published BOOLEAN NOT NULL DEFAULT true;
CREATE TABLE IF NOT EXISTS admin_team(email TEXT PRIMARY KEY,role TEXT NOT NULL CHECK(role IN ('admin','editor')),status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','invited','suspended')),permissions JSONB NOT NULL DEFAULT '{"canUploadEpisodes":true,"canEditPosters":true,"canDelete":false,"canModerateComments":true}'::jsonb,added_by TEXT NOT NULL DEFAULT 'system',created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
ALTER TABLE admin_team DROP CONSTRAINT IF EXISTS admin_team_status_check; ALTER TABLE admin_team ADD CONSTRAINT admin_team_status_check CHECK(status IN ('active','invited','suspended'));
CREATE TABLE IF NOT EXISTS admin_invites(email TEXT PRIMARY KEY,role TEXT NOT NULL CHECK(role IN ('admin','editor')),token_hash TEXT NOT NULL,expires_at TIMESTAMPTZ NOT NULL,accepted_at TIMESTAMPTZ,created_by TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS password_resets(id BIGSERIAL PRIMARY KEY,user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,token_hash TEXT NOT NULL UNIQUE,expires_at TIMESTAMPTZ NOT NULL,used_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS password_resets_user_idx ON password_resets(user_id); UPDATE admin_team t SET status='invited' WHERE t.status='suspended' AND EXISTS (SELECT 1 FROM admin_invites i WHERE i.email=t.email AND i.accepted_at IS NULL AND i.expires_at>now()) AND NOT EXISTS (SELECT 1 FROM users u WHERE lower(u.email)=t.email AND coalesce(u.password_hash,'')<>'');
CREATE TABLE IF NOT EXISTS admin_activity(id BIGSERIAL PRIMARY KEY,actor_email TEXT NOT NULL,actor_role TEXT NOT NULL,action TEXT NOT NULL,method TEXT NOT NULL,path TEXT NOT NULL,status_code INT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS admin_activity_created_at_idx ON admin_activity(created_at DESC);
CREATE TABLE IF NOT EXISTS video_reports(id BIGSERIAL PRIMARY KEY,episode_id INT REFERENCES episodes(id) ON DELETE SET NULL,anime_id INT REFERENCES anime(id) ON DELETE SET NULL,reporter_email TEXT DEFAULT '',video_url TEXT DEFAULT '',message TEXT DEFAULT '',status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','resolved','dismissed')),created_at TIMESTAMPTZ NOT NULL DEFAULT now(),resolved_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS site_settings(id INT PRIMARY KEY DEFAULT 1,site_name TEXT NOT NULL DEFAULT 'Primordial Streams',announcement TEXT NOT NULL DEFAULT '',social_links JSONB NOT NULL DEFAULT '{}'::jsonb,footer_text TEXT NOT NULL DEFAULT '',seo_title TEXT NOT NULL DEFAULT 'Primordial Streams',seo_description TEXT NOT NULL DEFAULT '',maintenance_mode BOOLEAN NOT NULL DEFAULT false,updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
INSERT INTO site_settings(id) VALUES(1) ON CONFLICT(id) DO NOTHING;
CREATE TABLE IF NOT EXISTS branding(id INT PRIMARY KEY DEFAULT 1,logo_url TEXT DEFAULT '',updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS notifications(id SERIAL PRIMARY KEY,user_id INT REFERENCES users(id) ON DELETE CASCADE,title TEXT NOT NULL,message TEXT NOT NULL,created_by INT REFERENCES users(id) ON DELETE SET NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS notification_type TEXT NOT NULL DEFAULT 'info';
CREATE TABLE IF NOT EXISTS notification_reads(notification_id INT NOT NULL REFERENCES notifications(id) ON DELETE CASCADE,user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,read_at TIMESTAMPTZ NOT NULL DEFAULT now(),PRIMARY KEY(notification_id,user_id));
CREATE TABLE IF NOT EXISTS comments(id SERIAL PRIMARY KEY,user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,anime_id INT NOT NULL REFERENCES anime(id) ON DELETE CASCADE,content TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','approved','rejected')),created_at TIMESTAMPTZ NOT NULL DEFAULT now(),reviewed_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS studios(id SERIAL PRIMARY KEY,name TEXT NOT NULL,slug TEXT UNIQUE NOT NULL,logo_url TEXT NOT NULL DEFAULT '',website_url TEXT NOT NULL DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT now());
ALTER TABLE studios ADD COLUMN IF NOT EXISTS website_url TEXT NOT NULL DEFAULT '';
ALTER TABLE anime ADD COLUMN IF NOT EXISTS studio_id INT REFERENCES studios(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS anime_studio_idx ON anime(studio_id);
INSERT INTO branding(id,logo_url) VALUES(1,'/assets/logo.jpg') ON CONFLICT(id) DO NOTHING;`);
const legacyCatalog = [["Dragon's Oath","Fantasy",24,9.2,"#f59e0b","#7c2d12",2022,"completed"],["Midnight Case","Mystery",12,8.9,"#38bdf8","#0f172a",2023,"ongoing"],["Sparkle Stage","Music",13,8.7,"#ec4899","#4c1d95",2024,"ongoing"],["Shadow Ninja","Action",26,8.8,"#6366f1","#0b1020",2025,"ongoing"],["Royal Hearts","Romance",12,8.5,"#f472b6","#581c87",2026,"ongoing"],["Titan Fall","Sci-Fi",25,8.6,"#fb923c","#1e3a8a",2022,"ongoing"],["Tea Time","Slice of Life",12,8.1,"#a16207","#292524",2023,"ongoing"],["Glimmer Woods","Fantasy",13,8.3,"#34d399","#064e3b",2024,"ongoing"],["Ring King","Sports",24,8.4,"#3b82f6","#7f1d1d",2025,"ongoing"],["Crimson Lord","Horror",12,8.7,"#dc2626","#1c0a0a",2026,"ongoing"],["Unit Seven","Sci-Fi",12,8.2,"#2dd4bf","#134e4a",2022,"ongoing"],["Sun Spike","Sports",13,8,"#fbbf24","#0369a1",2023,"ongoing"],["Neon Protocol","Sci-Fi",13,8.9,"#22d3ee","#581c87",2024,"ongoing"],["Starlight Academy","Fantasy",12,8.6,"#c084fc","#1e1b4b",2025,"ongoing"],["Tower of Spells","Fantasy",20,8.5,"#f59e0b","#312e81",2026,"ongoing"]];
for (const [title, genre, legacyEpisodes, rating, colorA, colorB, year, status] of legacyCatalog) {
  const slug = title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  await pool.query(
    "INSERT INTO anime(title,alt_title,slug,description,poster_url,banner_url,year,genres,rating,type,status,hindi_dub,subtitles,is_exclusive,characters) VALUES($1,'',$2,$3,'','',$4,$5,$6,'series',$7,false,true,false,$8::jsonb) ON CONFLICT(slug) DO NOTHING",
    [title, slug, "Anime details can be updated from the Admin Portal.", year, [genre], rating, status, JSON.stringify({legacyEpisodes, colorA, colorB})]
  );
}
if(process.env.ADMIN_EMAIL&&process.env.ADMIN_PASSWORD){const h=await bcrypt.hash(process.env.ADMIN_PASSWORD,12);await pool.query('insert into users(display_name,email,password_hash,role) values($1,$2,$3,$4) on conflict(email) do update set display_name=$1,password_hash=$3,role=$4',['PDI Admin',process.env.ADMIN_EMAIL.toLowerCase(),h,'admin'])}}
function token(u){return jwt.sign({id:u.id,role:u.role,email:u.email},JWT_SECRET,{expiresIn:'7d'})}
function auth(req,res,next){try{req.user=jwt.verify((req.headers.authorization||'').replace(/^Bearer /,''),JWT_SECRET);next()}catch{return res.status(401).json({error:'Unauthorized'})}}
async function effectiveStaff(email, dbRole){const normalized=String(email||'').toLowerCase();if(normalized==='primordialdubbers@gmail.com')return {role:'owner',status:'active',permissions:{canUploadEpisodes:true,canEditPosters:true,canDelete:true,canModerateComments:true}};const t=await pool.query('select role,status,permissions from admin_team where email=$1',[normalized]);if(t.rows[0])return t.rows[0];return null}
function admin(req,res,next){return auth(req,res,()=>{(async()=>{const u=(await pool.query('select id,email,role from users where id=$1',[req.user.id])).rows[0];if(!u)return res.status(403).json({error:'Staff access required'});const staff=await effectiveStaff(u.email,u.role);if(!staff||staff.status!=='active')return res.status(403).json({error:'This account has no active staff role'});req.staffEmail=u.email;req.staffRole=staff.role;req.staffPermissions=staff.permissions||{};const path=req.path.replace(/^\/api\/admin/,''),method=req.method;const ownerOnly=path.startsWith('/team')||path.startsWith('/settings')||path==='/branding';if(ownerOnly&&staff.role!=='owner')return res.status(403).json({error:'Owner access required'});if(staff.role==='editor'){const allowed=(method==='GET'&&['/anime','/episodes','/comments','/schedule','/whoami'].includes(path))||(path==='/anime'&&method==='POST')||(/^\/anime\/\d+$/.test(path)&&method==='PUT')||((path==='/episodes'||path==='/episodes/bulk')&&method==='POST')||(/^\/episodes\/\d+$/.test(path)&&method==='PUT')||(/^\/comments\/\d+$/.test(path)&&method==='PATCH');if(!allowed)return res.status(403).json({error:'Editor role cannot perform this action'});if(path.startsWith('/episodes')&&['POST','PUT'].includes(method)&&req.staffPermissions.canUploadEpisodes===false)return res.status(403).json({error:'Episode upload permission is disabled'});if(path.startsWith('/comments')&&method==='PATCH'&&req.staffPermissions.canModerateComments===false)return res.status(403).json({error:'Comment moderation permission is disabled'});if(path==='/anime'&&method==='POST'&&req.staffPermissions.canEditPosters===false&&(req.body.posterUrl||req.body.bannerUrl))return res.status(403).json({error:'Poster editing permission is disabled'});if(/^\/anime\/\d+$/.test(path)&&method==='PUT'&&req.staffPermissions.canEditPosters===false&&(req.body.posterUrl||req.body.bannerUrl))return res.status(403).json({error:'Poster editing permission is disabled'});}res.on('finish',()=>{if(req.path.startsWith('/api/admin/')&&['POST','PUT','PATCH','DELETE'].includes(method)&&res.statusCode<400)pool.query('insert into admin_activity(actor_email,actor_role,action,method,path,status_code) values($1,$2,$3,$4,$5,$6)',[req.staffEmail,req.staffRole,method+' '+path,method,path,res.statusCode]).catch(e=>console.error('Activity log write failed',e.message))});return next()})().catch(next)})}
app.get('/api/admin/whoami',admin,async(req,res)=>res.json({email:req.staffEmail,role:req.staffRole,permissions:req.staffPermissions}));
app.get('/api/admin/team',admin,async(req,res)=>{const{rows}=await pool.query("select t.email,t.role,t.status,t.permissions,t.created_at,t.updated_at,u.id user_id,u.display_name,u.last_login from admin_team t left join users u on lower(u.email)=t.email order by t.created_at desc");res.json([{email:'primordialdubbers@gmail.com',role:'owner',status:'active',permissions:{canUploadEpisodes:true,canEditPosters:true,canDelete:true,canModerateComments:true},display_name:'Owner',last_login:(await pool.query('select last_login from users where lower(email)=\'primordialdubbers@gmail.com\'')).rows[0]?.last_login},...rows.filter(r=>r.email!=='primordialdubbers@gmail.com')])});
app.post('/api/admin/team',admin,async(req,res)=>{const email=String(req.body.email||'').trim().toLowerCase(),role=String(req.body.role||'editor').toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return res.status(400).json({error:'Enter a valid email address'});if(email==='primordialdubbers@gmail.com')return res.status(400).json({error:'Owner role cannot be changed'});if(!['admin','editor'].includes(role))return res.status(400).json({error:'Role must be Admin or Editor'});const permissions={canUploadEpisodes:req.body.permissions?.canUploadEpisodes!==false,canEditPosters:req.body.permissions?.canEditPosters!==false,canDelete:false,canModerateComments:req.body.permissions?.canModerateComments!==false};const existing=(await pool.query('select id from users where lower(email)=$1',[email])).rows[0];const status=req.body.status==='suspended'?'suspended':'active';const{rows}=await pool.query("insert into admin_team(email,role,status,permissions,added_by) values($1,$2,$3,$4::jsonb,$5) on conflict(email) do update set role=excluded.role,status=excluded.status,permissions=excluded.permissions,updated_at=now() returning *",[email,role,existing?status:'invited',JSON.stringify(permissions),req.staffEmail]);if(existing){await pool.query('delete from admin_invites where email=$1',[email]);return res.status(200).json({...rows[0],inviteRequired:false,message:'Existing account assigned the selected role.'})}const rawToken=crypto.randomBytes(32).toString('hex'),tokenHash=crypto.createHash('sha256').update(rawToken).digest('hex');await pool.query("insert into admin_invites(email,role,token_hash,expires_at,created_by,accepted_at) values($1,$2,$3,now()+interval '7 days',$4,null) on conflict(email) do update set role=excluded.role,token_hash=excluded.token_hash,expires_at=excluded.expires_at,created_by=excluded.created_by,created_at=now(),accepted_at=null",[email,role,tokenHash,req.staffEmail]);const base=String(process.env.FRONTEND_URL||'https://primordialstreams.up.railway.app').split(',')[0].replace(/\/$/,'');return res.status(201).json({...rows[0],inviteRequired:true,inviteUrl:base+'/accept-invite?invite='+encodeURIComponent(rawToken)+'&email='+encodeURIComponent(email),expiresInDays:7,message:'Invite created. Copy and send the secure invite link to the invited email.'})});
app.post('/api/admin/team/:email/invite',admin,async(req,res)=>{const email=decodeURIComponent(req.params.email).trim().toLowerCase();if(email==='primordialdubbers@gmail.com')return res.status(403).json({error:'Owner cannot be invited'});const member=(await pool.query("select email,role,status from admin_team where email=$1",[email])).rows[0];if(!member)return res.sendStatus(404);if(member.status!=='invited')return res.status(409).json({error:'Only pending invited members can have their invite link regenerated.'});const rawToken=crypto.randomBytes(32).toString('hex'),tokenHash=crypto.createHash('sha256').update(rawToken).digest('hex');const result=await pool.query("update admin_invites set role=$1,token_hash=$2,expires_at=now()+interval '7 days',created_by=$3,created_at=now(),accepted_at=null where email=$4 and accepted_at is null returning email",[member.role,tokenHash,req.staffEmail,email]);if(!result.rowCount)return res.status(409).json({error:'No pending invite exists for this member.'});const base=String(process.env.FRONTEND_URL||'https://primordialstreams.up.railway.app').split(',')[0].replace(/\/$/,'');return res.json({email,role:member.role,status:member.status,inviteRequired:true,inviteUrl:base+'/accept-invite?invite='+encodeURIComponent(rawToken)+'&email='+encodeURIComponent(email),expiresInDays:7,message:'Invite link regenerated. The previous link is invalid.'})});
app.patch('/api/admin/team/:email',admin,async(req,res)=>{const email=decodeURIComponent(req.params.email).toLowerCase();if(email==='primordialdubbers@gmail.com')return res.status(403).json({error:'Owner cannot be demoted, suspended, or removed'});const role=req.body.role===undefined?null:String(req.body.role).toLowerCase(),status=req.body.status===undefined?null:String(req.body.status),permissions=req.body.permissions;if(role&&!['admin','editor'].includes(role))return res.status(400).json({error:'Invalid role'});if(status&&!['active','suspended'].includes(status))return res.status(400).json({error:'Invalid status'});const old=(await pool.query('select * from admin_team where email=$1',[email])).rows[0];if(!old)return res.sendStatus(404);const merged=permissions?{...old.permissions,...permissions,canDelete:false}:old.permissions;const{rows}=await pool.query('update admin_team set role=coalesce($1,role),status=coalesce($2,status),permissions=$3::jsonb,updated_at=now() where email=$4 returning *',[role,status,JSON.stringify(merged),email]);if(status==='suspended')await pool.query('delete from admin_invites where email=$1',[email]);res.json(rows[0])});
app.delete('/api/admin/team/:email',admin,async(req,res)=>{const email=decodeURIComponent(req.params.email).toLowerCase();if(email==='primordialdubbers@gmail.com')return res.status(403).json({error:'Owner cannot be removed'});const result=await pool.query('delete from admin_team where email=$1',[email]);await pool.query('delete from admin_invites where email=$1',[email]);if(!result.rowCount)return res.sendStatus(404);res.sendStatus(204)});
app.get('/api/admin/activity',admin,async(req,res)=>{const{rows}=await pool.query('select id,actor_email,actor_role,action,method,path,status_code,created_at from admin_activity order by created_at desc limit 500');res.json(rows)});
app.get('/api/admin/settings',admin,async(req,res)=>{const{rows}=await pool.query('select * from site_settings where id=1');res.json(rows[0]||{})});
app.put('/api/admin/settings',admin,async(req,res)=>{const x=req.body;const{rows}=await pool.query('update site_settings set site_name=$1,announcement=$2,social_links=$3::jsonb,footer_text=$4,seo_title=$5,seo_description=$6,maintenance_mode=$7,updated_at=now() where id=1 returning *',[String(x.siteName||'Primordial Streams').slice(0,120),String(x.announcement||'').slice(0,1000),JSON.stringify(x.socialLinks||{}),String(x.footerText||'').slice(0,2000),String(x.seoTitle||'').slice(0,180),String(x.seoDescription||'').slice(0,320),!!x.maintenanceMode]);res.json(rows[0])});
app.get('/api/admin/reports',admin,async(req,res)=>{const{rows}=await pool.query('select r.*,a.title anime_title,e.title episode_title from video_reports r left join anime a on a.id=r.anime_id left join episodes e on e.id=r.episode_id order by r.created_at desc limit 500');res.json(rows)});
app.patch('/api/admin/reports/:id',admin,async(req,res)=>{const status=String(req.body.status||'');if(!['pending','resolved','dismissed'].includes(status))return res.status(400).json({error:'Invalid report status'});const{rows}=await pool.query('update video_reports set status=$1,resolved_at=case when $1=\'pending\' then null else now() end where id=$2 returning *',[status,req.params.id]);if(!rows[0])return res.sendStatus(404);res.json(rows[0])});
app.get('/api/admin/backup.json',admin,async(req,res)=>{const [a,e]=await Promise.all([pool.query('select * from anime order by id'),pool.query('select * from episodes order by id')]);res.json({exportedAt:new Date().toISOString(),anime:a.rows,episodes:e.rows})});
app.get('/api/admin/anime.csv',admin,async(req,res)=>{const{rows}=await pool.query('select id,title,slug,type,year,status,is_published,poster_url,created_at from anime order by id');const q=v=>'"'+String(v??'').replaceAll('"','""')+'"';res.type('text/csv').send('id,title,slug,type,year,status,is_published,poster_url,created_at\\n'+rows.map(r=>Object.values(r).map(q).join(',')).join('\\n'))});
app.post('/api/reports/video',auth,async(req,res)=>{const animeId=Number(req.body.animeId)||null,episodeId=Number(req.body.episodeId)||null,message=String(req.body.message||'').trim().slice(0,1000),videoUrl=String(req.body.videoUrl||'').trim().slice(0,2000);const{rows}=await pool.query('insert into video_reports(anime_id,episode_id,reporter_email,video_url,message) values($1,$2,$3,$4,$5) returning id,status,created_at',[animeId,episodeId,req.user.email||'',videoUrl,message]);res.status(201).json(rows[0])});
app.get('/api/health',async(req,res)=>{try{await pool.query('select 1');res.json({ok:true})}catch{res.status(503).json({ok:false})}});
app.post('/api/auth/register',async(req,res)=>{const{displayName,email,password}=req.body;if(!displayName||!email||!password)return res.status(400).json({error:'Missing fields'});try{const h=await bcrypt.hash(password,12);const{rows}=await pool.query('insert into users(display_name,email,password_hash) values($1,$2,$3) returning id,display_name,email,role,created_at',[String(displayName).trim().slice(0,100),String(email).trim().toLowerCase(),h]);res.status(201).json({token:token(rows[0]),user:rows[0]})}catch{res.status(409).json({error:'Email already registered'})}});
app.post('/api/auth/team-invite/accept',authLimiter,async(req,res)=>{const email=String(req.body.email||'').trim().toLowerCase(),inviteToken=String(req.body.inviteToken||''),password=String(req.body.password||''),displayName=String(req.body.displayName||email.split('@')[0]).trim().slice(0,100);if(!email||!inviteToken||password.length<10)return res.status(400).json({error:'Invite link, invited email, and a password of at least 10 characters are required.'});const found=(await pool.query('select * from admin_invites where email=$1 and accepted_at is null and expires_at>now()',[email])).rows[0];const candidateHash=crypto.createHash('sha256').update(inviteToken).digest('hex');if(!found||!crypto.timingSafeEqual(Buffer.from(found.token_hash),Buffer.from(candidateHash)))return res.status(403).json({error:'Access denied: no valid invite exists for this email.'});const h=await bcrypt.hash(password,12);const client=await pool.connect();try{await client.query('BEGIN');const existing=(await client.query('select id from users where lower(email)=$1 for update',[email])).rows[0];if(existing){await client.query("UPDATE users SET password_hash=$1,display_name=CASE WHEN display_name IS NULL OR display_name='' THEN $2 ELSE display_name END WHERE id=$3",[h,displayName,existing.id])}else{await client.query("INSERT INTO users(display_name,email,password_hash,role) VALUES($1,$2,$3,'user')",[displayName,email,h])}await client.query("UPDATE admin_team SET status='active' WHERE email=$1",[email]);await client.query("UPDATE admin_invites SET accepted_at=now(),token_hash='accepted' WHERE email=$1",[email]);await client.query('COMMIT')}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}return res.json({message:'Invite accepted. You can now sign in with your new password.'})});
// Admin MFA is optional unless ADMIN_MFA_CODE is explicitly configured.

// Password reset: tokens are hashed in the database, short-lived, single-use, and never returned by the API.
app.post('/api/auth/forgot-password',authLimiter,async(req,res)=>{
  const email=String(req.body?.email||'').trim().toLowerCase();
  if(!email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) return res.status(400).json({error:'Enter a valid email address.'});
  const generic={message:'If an account exists for that email, a password reset link will be sent.'};
  const user=(await pool.query('select id,email from users where lower(email)=$1',[email])).rows[0];
  if(!user) return res.json(generic);

  const hasBrevo=Boolean(process.env.BREVO_API_KEY && process.env.PASSWORD_RESET_FROM);
  const hasResend=Boolean(process.env.RESEND_API_KEY && process.env.PASSWORD_RESET_FROM);
  if(!hasBrevo && !hasResend) return res.status(503).json({error:'Password reset email is not configured yet. Please contact the site owner.'});

  const raw=crypto.randomBytes(32).toString('hex');
  const tokenHash=crypto.createHash('sha256').update(raw).digest('hex');
  await pool.query('update password_resets set used_at=now() where user_id=$1 and used_at is null',[user.id]);
  await pool.query("insert into password_resets(user_id,token_hash,expires_at) values($1,$2,now()+interval '30 minutes')",[user.id,tokenHash]);

  const base=String(process.env.FRONTEND_URL||'https://primordialstreams.up.railway.app').split(',')[0].replace(/\/$/,'');
  const resetUrl=base+'/#/reset-password/'+raw;
  const html='<div style="font-family:Arial,sans-serif;max-width:520px;margin:auto;color:#172033"><h2>Reset your password</h2><p>We received a request to reset your Primordial Streams password.</p><p><a href="'+resetUrl+'" style="display:inline-block;padding:12px 18px;background:#2f6bff;color:#fff;border-radius:8px;text-decoration:none">Reset password</a></p><p>This link expires in 30 minutes and can only be used once. If you did not request this, ignore this email.</p></div>';
  const text='Reset your Primordial Streams password: '+resetUrl+'\n\nThis link expires in 30 minutes and can only be used once.';

  try {
    if(hasBrevo){
      const mail=await fetch('https://api.brevo.com/v3/smtp/email',{
        method:'POST',
        headers:{accept:'application/json','api-key':process.env.BREVO_API_KEY,'Content-Type':'application/json'},
        body:JSON.stringify({
          sender:{email:process.env.PASSWORD_RESET_FROM,name:process.env.PASSWORD_RESET_FROM_NAME||'Primordial Streams'},
          to:[{email}],
          subject:'Reset your Primordial Streams password',
          htmlContent:html,
          textContent:text
        })
      });
      if(!mail.ok){
        const details=await mail.text().catch(()=> '');
        throw new Error('Brevo '+mail.status+': '+details.slice(0,300));
      }
    } else {
      const mail=await fetch('https://api.resend.com/emails',{
        method:'POST',
        headers:{Authorization:'Bearer '+process.env.RESEND_API_KEY,'Content-Type':'application/json'},
        body:JSON.stringify({
          from:process.env.PASSWORD_RESET_FROM,
          to:[email],
          subject:'Reset your Primordial Streams password',
          html,
          text
        })
      });
      if(!mail.ok){
        const details=await mail.text().catch(()=> '');
        throw new Error('Resend '+mail.status+': '+details.slice(0,300));
      }
    }
  } catch(e) {
    console.error('Password reset email provider error:',e?.message||'Unknown email error');
    await pool.query('update password_resets set used_at=now() where token_hash=$1',[tokenHash]);
    return res.status(502).json({error:'Reset email could not be sent. Please check the email service settings and try again.'});
  }
  return res.json(generic);
});
app.post('/api/auth/reset-password',authLimiter,async(req,res)=>{
  const raw=String(req.body?.token||''),password=String(req.body?.password||'');
  if(!raw || !/^[a-f0-9]{64}$/i.test(raw)) return res.status(400).json({error:'This reset link is invalid. Request a new one.'});
  if(password.length<10) return res.status(400).json({error:'Password must be at least 10 characters long.'});
  const hash=crypto.createHash('sha256').update(raw).digest('hex');
  const client=await pool.connect();
  try{
    await client.query('BEGIN');
    const reset=(await client.query('select id,user_id from password_resets where token_hash=$1 and used_at is null and expires_at>now() for update',[hash])).rows[0];
    if(!reset){await client.query('ROLLBACK');return res.status(400).json({error:'This reset link has expired or was already used. Request a new one.'});}
    const passHash=await bcrypt.hash(password,12);
    await client.query('update users set password_hash=$1 where id=$2',[passHash,reset.user_id]);
    await client.query('update password_resets set used_at=now() where user_id=$1 and used_at is null',[reset.user_id]);
    await client.query('COMMIT');
    return res.json({message:'Password updated successfully. You can now sign in.'});
  }catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}
});
app.post('/api/auth/login',async(req,res)=>{const{email,password,mfaCode}=req.body;const{rows}=await pool.query('select * from users where email=$1',[String(email||'').toLowerCase()]);if(!rows[0]||!(await bcrypt.compare(password||'',rows[0].password_hash)))return res.status(401).json({error:'Invalid credentials'});if(rows[0].role==='user'&&rows[0].is_banned)return res.status(403).json({error:'This account has been suspended'});if(rows[0].role==='admin'&&process.env.ADMIN_MFA_CODE&&String(mfaCode||'')!==String(process.env.ADMIN_MFA_CODE))return res.status(401).json({error:'Invalid MFA / Security Passcode'});const u=rows[0];delete u.password_hash;await pool.query('update users set last_login=now() where id=$1',[u.id]);const staff=await effectiveStaff(u.email,u.role);if(staff&&staff.status==='active')u.adminRole=staff.role;res.json({token:token(u),user:u})});
app.get('/api/auth/google/config',(req,res)=>res.json({clientId:process.env.GOOGLE_CLIENT_ID||''}));
app.post('/api/auth/google',async(req,res)=>{try{const credential=String(req.body.credential||'');if(!process.env.GOOGLE_CLIENT_ID)return res.status(503).json({error:'Google OAuth Client ID is not configured on the server'});if(!credential)return res.status(400).json({error:'Missing Google credential'});const verify=await fetch('https://oauth2.googleapis.com/tokeninfo?id_token='+encodeURIComponent(credential));if(!verify.ok)return res.status(401).json({error:'Google credential could not be verified'});const g=await verify.json();if(g.aud!==process.env.GOOGLE_CLIENT_ID||g.email_verified!=='true'||!g.email)return res.status(401).json({error:'Google account verification failed'});const email=g.email.toLowerCase(),displayName=g.name||g.given_name||email.split('@')[0],avatar=g.picture||'';const hash=await bcrypt.hash(crypto.randomUUID(),12);const result=await pool.query("insert into users(display_name,email,password_hash,avatar_url) values($1,$2,$3,$4) on conflict(email) do update set display_name=excluded.display_name,avatar_url=case when excluded.avatar_url<>'' then excluded.avatar_url else users.avatar_url end returning id,display_name,email,role,created_at,avatar_url",[displayName,email,hash,avatar]);const banned=await pool.query('select is_banned from users where id=$1',[result.rows[0].id]);if(banned.rows[0]?.is_banned)return res.status(403).json({error:'This account has been suspended'});res.json({token:token(result.rows[0]),user:result.rows[0]})}catch(e){console.error('Google sign-in failed',e);res.status(500).json({error:'Google sign-in failed. Please try again.'})}});
app.get('/api/me',auth,async(req,res)=>{const{rows}=await pool.query('select id,display_name,email,role,created_at,avatar_url from users where id=$1',[req.user.id]);res.json(rows[0])});
app.put('/api/me',auth,async(req,res)=>{const displayName=String(req.body.displayName||'').trim();const avatarUrl=req.body.avatarUrl===undefined?null:String(req.body.avatarUrl);if(!displayName)return res.status(400).json({error:'Username is required'});if(avatarUrl&&(!avatarUrl.startsWith('data:image/')||avatarUrl.length>6*1024*1024))return res.status(400).json({error:'Invalid profile image or image is too large'});const{rows}=await pool.query('update users set display_name=$1,avatar_url=coalesce($2,avatar_url) where id=$3 returning id,display_name,email,role,created_at,avatar_url',[displayName,avatarUrl,req.user.id]);res.json(rows[0])});
app.get('/api/anime',async(req,res)=>{const{rows}=await pool.query(`select a.*,s.name as studio_name,s.logo_url as studio_logo_url,s.website_url as studio_website_url,(select count(*)::int from episodes e where e.anime_id=a.id and e.is_published=true) as episode_count,coalesce((select json_agg(json_build_object('id',e.id,'seasonNumber',e.season_number,'episodeNumber',e.episode_number,'title',e.title,'video_url',e.video_url,'thumbnail_url',e.thumbnail_url) order by e.season_number,e.episode_number) from episodes e where e.anime_id=a.id and e.is_published=true),'[]'::json) as episodes from anime a left join studios s on s.id=a.studio_id where a.is_published=true order by a.is_featured desc,a.featured_order asc,a.is_exclusive desc,a.created_at desc`);res.json(rows)});
app.get('/api/anime/:slug',async(req,res)=>{const a=(await pool.query('select a.*,s.name as studio_name,s.logo_url as studio_logo_url,s.website_url as studio_website_url from anime a left join studios s on s.id=a.studio_id where a.slug=$1 and a.is_published=true',[req.params.slug])).rows[0];if(!a)return res.sendStatus(404);a.episodes=(await pool.query('select * from episodes where anime_id=$1 and is_published=true order by season_number,episode_number',[a.id])).rows;res.json(a)});
// Studios: public read, staff (owner/admin) add + edit only. There is intentionally no delete route.
function studioSlug(v){return String(v||'').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
async function studioIdOf(v){const n=Number(v);if(!Number.isInteger(n)||n<1)return null;const r=await pool.query('select id from studios where id=$1',[n]);return r.rows[0]?n:null}
function cleanStudio(body){const name=String(body?.name||'').trim().slice(0,80);if(!name)return{error:'Studio name is required'};const hasLogo=body&&(body.logoUrl!==undefined||body.logo_url!==undefined);const logo=hasLogo?String(body.logoUrl??body.logo_url??'').trim():undefined;if(logo!==undefined&&(logo.length>1800000||(logo&&!(/^(https?:\/\/|\/)/i.test(logo)||/^data:image\/(webp|png|jpeg|jpg);base64,[A-Za-z0-9+/=]+$/i.test(logo)))))return{error:'Use an image URL or upload a PNG/JPG/WEBP logo under 1.3 MB.'};const hasWebsite=body&&(body.websiteUrl!==undefined||body.website_url!==undefined);const website=hasWebsite?String(body.websiteUrl??body.website_url??'').trim().slice(0,500):undefined;if(website&&!/^https?:\/\//i.test(website))return{error:'Studio website URL must start with http:// or https://'};return{name,logo,website}}
app.get('/api/studios',async(req,res)=>{const{rows}=await pool.query('select s.id,s.name,s.slug,s.logo_url,s.website_url,(select count(*)::int from anime a where a.studio_id=s.id and a.is_published=true) as anime_count from studios s order by lower(s.name)');res.json(rows)});
app.get('/api/studios/:slug',async(req,res)=>{const s=(await pool.query('select id,name,slug,logo_url,website_url from studios where slug=$1',[req.params.slug])).rows[0];if(!s)return res.sendStatus(404);const{rows}=await pool.query(`select a.*,(select count(*)::int from episodes e where e.anime_id=a.id and e.is_published=true) as episode_count,coalesce((select json_agg(json_build_object('id',e.id,'seasonNumber',e.season_number,'episodeNumber',e.episode_number,'title',e.title,'video_url',e.video_url,'thumbnail_url',e.thumbnail_url) order by e.season_number,e.episode_number) from episodes e where e.anime_id=a.id and e.is_published=true),'[]'::json) as episodes from anime a where a.studio_id=$1 and a.is_published=true order by a.is_featured desc,a.featured_order asc,a.is_exclusive desc,a.created_at desc`,[s.id]);res.json({...s,anime:rows})});
app.get('/api/admin/studios',admin,async(req,res)=>{const{rows}=await pool.query('select s.id,s.name,s.slug,s.logo_url,s.website_url,s.created_at,(select count(*)::int from anime a where a.studio_id=s.id) as anime_count from studios s order by lower(s.name)');res.json(rows)});
app.post('/api/admin/studios',admin,async(req,res)=>{const c=cleanStudio(req.body);if(c.error)return res.status(400).json({error:c.error});const slug=studioSlug(req.body.slug||c.name)||('studio-'+crypto.randomBytes(3).toString('hex'));try{const{rows}=await pool.query('insert into studios(name,slug,logo_url,website_url) values($1,$2,$3,$4) returning id,name,slug,logo_url,website_url,created_at',[c.name,slug,c.logo||'',c.website||'']);res.status(201).json({...rows[0],anime_count:0})}catch(e){if(e.code==='23505')return res.status(409).json({error:'A studio with this name already exists'});throw e}});
app.put('/api/admin/studios/:id',admin,async(req,res)=>{const c=cleanStudio(req.body);if(c.error)return res.status(400).json({error:c.error});const id=Number(req.params.id);if(!Number.isInteger(id)||id<1)return res.sendStatus(404);const{rows}=await pool.query('update studios set name=$1,logo_url=coalesce($2,logo_url),website_url=coalesce($3,website_url) where id=$4 returning id,name,slug,logo_url,website_url,created_at',[c.name,c.logo===undefined?null:c.logo,c.website===undefined?null:c.website,id]);if(!rows[0])return res.sendStatus(404);res.json(rows[0])});
app.get('/api/site-settings',async(req,res)=>{const{rows}=await pool.query('select site_name,announcement,social_links,footer_text,seo_title,seo_description,maintenance_mode from site_settings where id=1');res.json(rows[0]||{site_name:'Primordial Streams',announcement:'',social_links:{},footer_text:'',seo_title:'Primordial Streams',seo_description:'',maintenance_mode:false})});
app.get('/api/branding',async(req,res)=>{const{rows}=await pool.query('select logo_url from branding where id=1');res.json({logoUrl:rows[0]?.logo_url||'/assets/logo.jpg'})});
app.get('/api/admin/anime',admin,async(req,res)=>{const{rows}=await pool.query('select a.*,(select count(*)::int from episodes e where e.anime_id=a.id) episode_count from anime a order by is_exclusive desc,created_at desc');res.json(rows)});
app.get('/api/admin/users',admin,async(req,res)=>{const q=String(req.query.q||'').trim();const{rows}=await pool.query(`select id,display_name,email,role,created_at,avatar_url,last_login,is_banned from users where role='user' ${q?'and (display_name ilike $1 or email ilike $1)':''} order by created_at desc`,q?[`%${q}%`]:[]);res.json(rows)});
app.get('/api/admin/users/:id',admin,async(req,res)=>{const{rows}=await pool.query("select id,display_name,email,role,created_at,avatar_url,last_login,is_banned from users where id=$1 and role='user'",[req.params.id]);if(!rows[0])return res.sendStatus(404);res.json(rows[0])});
app.get('/api/admin/users.csv',admin,async(req,res)=>{const{rows}=await pool.query("select id,display_name,email,role,created_at from users where role='user' order by created_at desc");res.type('text/csv').send('id,display_name,email,role,created_at\\n'+rows.map(r=>[r.id,r.display_name,r.email,r.role,r.created_at.toISOString()].map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\\n'))});
app.put('/api/admin/branding',admin,async(req,res)=>{const logoUrl=String(req.body.logoUrl||'');if(!logoUrl)return res.status(400).json({error:'logoUrl required'});await pool.query('update branding set logo_url=$1,updated_at=now() where id=1',[logoUrl]);res.json({logoUrl})});
app.post('/api/admin/anime',admin,async(req,res)=>{const x=req.body;const studioId=await studioIdOf(x.studioId);const cast=Array.isArray(x.voiceCast)?x.voiceCast.slice(0,80).map(ch=>({...ch,name:String(ch.name||'').slice(0,160),actor:String(ch.actor||'').slice(0,160),language:String(ch.language||'Hindi').slice(0,40),role:ch.role==='supporting'?'supporting':'main',image:String(ch.image||'').slice(0,1600000),actorImage:String(ch.actorImage||'').slice(0,1600000),audioSampleUrl:String(ch.audioSampleUrl||'').slice(0,420000)})).filter(ch=>ch.name):[];const{rows}=await pool.query('insert into anime(title,alt_title,slug,description,poster_url,banner_url,year,genres,rating,type,status,hindi_dub,subtitles,is_exclusive,characters,voice_cast,is_published,is_featured,featured_order,studio_id) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20) returning *',[x.title,x.altTitle||'',x.slug,x.description||'',x.posterUrl||'',x.bannerUrl||'',x.year||null,x.genres||[],x.rating||null,x.type||'series',x.status||'ongoing',!!x.hindiDub,x.subtitles!==false,!!x.isExclusive,JSON.stringify(Array.isArray(x.characters)?x.characters:[]),JSON.stringify(cast),x.isPublished!==false,!!x.isFeatured,Number(x.featuredOrder)||0,studioId]);res.status(201).json(rows[0])});
app.put('/api/admin/anime/:id',admin,async(req,res)=>{const x=req.body;const hasStudio=Object.prototype.hasOwnProperty.call(x,'studioId');const studioId=hasStudio?await studioIdOf(x.studioId):null;const cast=Array.isArray(x.voiceCast)?x.voiceCast.slice(0,80).map(ch=>({...ch,audioSampleUrl:String(ch.audioSampleUrl||'').slice(0,420000)})):[];const{rows}=await pool.query('update anime set title=$1,alt_title=$2,slug=$3,description=$4,poster_url=$5,banner_url=$6,year=$7,genres=$8,rating=$9,type=$10,status=$11,hindi_dub=$12,subtitles=$13,is_exclusive=$14,voice_cast=$15,is_published=$16,is_featured=$17,featured_order=$18,studio_id=case when $19::boolean then $20::int else studio_id end where id=$21 returning *',[x.title,x.altTitle||'',x.slug,x.description||'',x.posterUrl||'',x.bannerUrl||'',x.year||null,x.genres||[],x.rating||null,x.type||'series',x.status||'ongoing',!!x.hindiDub,x.subtitles!==false,!!x.isExclusive,JSON.stringify(cast),x.isPublished!==false,!!x.isFeatured,Number(x.featuredOrder)||0,hasStudio,studioId,req.params.id]);if(!rows[0])return res.sendStatus(404);res.json(rows[0])});
app.delete('/api/admin/anime/:id',admin,async(req,res)=>{await pool.query('delete from anime where id=$1',[req.params.id]);res.sendStatus(204)});
app.get('/api/notifications',auth,async(req,res)=>{const{rows}=await pool.query('select n.id,n.title,n.message,n.notification_type,n.created_at,exists(select 1 from notification_reads nr where nr.notification_id=n.id and nr.user_id=$1) as is_read from notifications n where n.user_id is null or n.user_id=$1 order by n.created_at desc limit 100',[req.user.id]);res.json(rows)});
app.patch('/api/notifications/:id/read',auth,async(req,res)=>{const{rows}=await pool.query('insert into notification_reads(notification_id,user_id) select n.id,$1 from notifications n where n.id=$2 and (n.user_id is null or n.user_id=$1) on conflict(notification_id,user_id) do nothing returning notification_id,read_at',[req.user.id,req.params.id]);if(rows[0])return res.json({id:Number(req.params.id),is_read:true,read_at:rows[0].read_at});const check=await pool.query('select 1 from notification_reads nr join notifications n on n.id=nr.notification_id where nr.notification_id=$1 and nr.user_id=$2 and (n.user_id is null or n.user_id=$2)',[req.params.id,req.user.id]);if(check.rowCount)return res.json({id:Number(req.params.id),is_read:true});return res.sendStatus(404)});
app.get('/api/admin/notifications',admin,async(req,res)=>{const{rows}=await pool.query('select n.id,n.user_id,n.title,n.message,n.notification_type,n.created_at,u.display_name user_name,u.email user_email,coalesce((select count(*)::int from notification_reads nr where nr.notification_id=n.id),0) as read_count from notifications n left join users u on u.id=n.user_id order by n.created_at desc limit 300');res.json(rows)});
app.post('/api/admin/notifications',admin,async(req,res)=>{const title=String(req.body.title||'').trim(),message=String(req.body.message||'').trim(),type=String(req.body.type||'info');const rawIds=Array.isArray(req.body.userIds)?req.body.userIds:(req.body.userId==null||req.body.userId===''?[]:[req.body.userId]);const userIds=[...new Set(rawIds.map(Number))];if(!title||!message)return res.status(400).json({error:'Title and message are required'});if(title.length>120||message.length>2000)return res.status(400).json({error:'Title must be ≤120 characters and message ≤2000 characters'});if(!['info','announcement','release','warning','success'].includes(type))return res.status(400).json({error:'Invalid notification type'});if(rawIds.length>500||userIds.some(id=>!Number.isInteger(id)||id<1))return res.status(400).json({error:'Invalid recipient selection'});if(userIds.length){const check=await pool.query("select count(*)::int count from users where id=any($1::int[]) and role='user'",[userIds]);if(check.rows[0].count!==userIds.length)return res.status(400).json({error:'One or more selected recipients are not registered users'});}const client=await pool.connect();try{await client.query('BEGIN');const targets=userIds.length?userIds:[null];const created=[];for(const userId of targets){const{rows}=await client.query('insert into notifications(user_id,title,message,notification_type,created_by) values($1,$2,$3,$4,$5) returning id,user_id,title,message,notification_type,created_at',[userId,title,message,type,req.user.id]);created.push(rows[0]);}await client.query('COMMIT');res.status(201).json({count:created.length,notifications:created})}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}});
app.delete('/api/admin/notifications/:id',admin,async(req,res)=>{await pool.query('delete from notifications where id=$1',[req.params.id]);res.sendStatus(204)});
app.get('/api/anime/:slug/comments',async(req,res)=>{const{rows}=await pool.query("select c.id,c.content,c.created_at,u.display_name from comments c join anime a on a.id=c.anime_id join users u on u.id=c.user_id where a.slug=$1 and c.status='approved' order by c.created_at desc limit 100",[req.params.slug]);res.json(rows)});
app.post('/api/anime/:slug/comments',auth,async(req,res)=>{const content=String(req.body.content||'').trim();if(!content||content.length>2000)return res.status(400).json({error:'Comment must be 1–2000 characters'});const a=await pool.query('select id from anime where slug=$1',[req.params.slug]);if(!a.rowCount)return res.sendStatus(404);const{rows}=await pool.query("insert into comments(user_id,anime_id,content,status) values($1,$2,$3,'pending') returning id,content,status,created_at",[req.user.id,a.rows[0].id,content]);res.status(201).json({...rows[0],message:'Your comment is awaiting admin approval.'})});
app.get('/api/admin/comments',admin,async(req,res)=>{const status=['pending','approved','rejected'].includes(req.query.status)?req.query.status:null;const sql="select c.id,c.content,c.status,c.created_at,c.reviewed_at,u.id user_id,u.display_name user_name,u.email user_email,a.title anime_title from comments c join users u on u.id=c.user_id join anime a on a.id=c.anime_id "+(status?'where c.status=$1 ':'')+"order by case c.status when 'pending' then 0 when 'approved' then 1 else 2 end,c.created_at desc limit 500";const{rows}=await pool.query(sql,status?[status]:[]);res.json(rows)});
app.patch('/api/admin/comments/:id',admin,async(req,res)=>{const status=String(req.body.status||'');if(!['approved','rejected'].includes(status))return res.status(400).json({error:'Status must be approved or rejected'});const{rows}=await pool.query('update comments set status=$1,reviewed_at=now() where id=$2 returning id,status,reviewed_at',[status,req.params.id]);if(!rows[0])return res.sendStatus(404);res.json(rows[0])});
app.delete('/api/admin/comments/:id',admin,async(req,res)=>{await pool.query('delete from comments where id=$1',[req.params.id]);res.sendStatus(204)});
app.get('/api/admin/overview',admin,async(req,res)=>{try{const {rows}=await pool.query(`
SELECT
 (SELECT count(*)::int FROM anime) AS total_anime,
 (SELECT count(*)::int FROM anime WHERE lower(type) IN ('movie','film')) AS total_movies,
 (SELECT count(*)::int FROM episodes) AS total_episodes,
 (SELECT count(*)::int FROM anime WHERE lower(type) IN ('web-series','web series','webseries')) AS total_web_series,
 (SELECT count(*)::int FROM anime WHERE lower(status) IN ('ongoing','on-air','airing')) AS ongoing_titles,
 (SELECT count(*)::int FROM anime WHERE lower(status) IN ('completed','complete','finished')) AS completed_titles,
 (SELECT count(*)::int FROM anime WHERE lower(status) IN ('upcoming','coming-soon','coming soon')) AS coming_soon_titles,
 (SELECT count(*)::int FROM users WHERE role='user') AS registered_users,
 (SELECT count(*)::int FROM users WHERE role='user' AND created_at >= now()-interval '7 days') AS new_users_7d,
 (SELECT count(DISTINCT user_id)::int FROM progress WHERE updated_at >= now()-interval '30 days') AS active_users_30d,
 (SELECT count(*)::int FROM progress) AS tracked_plays,
 (SELECT count(*)::int FROM watchlist) AS watchlist_additions,
 (SELECT count(*)::int FROM comments WHERE status='pending') AS pending_comments,
 (SELECT count(*)::int FROM video_reports WHERE status='pending') AS pending_player_reports,
 (SELECT count(*)::int FROM notifications n WHERE NOT EXISTS (SELECT 1 FROM notification_reads nr WHERE nr.notification_id=n.id)) AS unread_notifications,
 (SELECT count(*)::int FROM studios) AS total_studios,
 (SELECT count(*)::int FROM anime WHERE is_published=false) AS drafts,
 (SELECT count(*)::int FROM episodes WHERE is_published=false) AS unpublished_episodes
`);const recent=await pool.query('SELECT id,actor_email,actor_role,action,method,path,status_code,created_at FROM admin_activity ORDER BY created_at DESC LIMIT 8');res.set('Cache-Control','no-store');res.json({metrics:rows[0],recentActivity:recent.rows,generatedAt:new Date().toISOString(),definitions:{tracked_plays:'Count of saved playback-progress records; not a verified stream-start count.',active_users_30d:'Distinct users with a playback-progress update in the last 30 days.',new_users_7d:'User accounts created in the last 7 days.'}})}catch(error){console.error('Admin overview query failed:',error.message);res.status(500).json({error:'Unable to load live dashboard metrics.'})}});
app.get('/api/admin/health',admin,async(req,res)=>{const checks={api:true,database:false};try{await pool.query('SELECT 1');checks.database=true;res.set('Cache-Control','no-store');res.json({status:'healthy',checks,checkedAt:new Date().toISOString(),uptimeSeconds:Math.floor(process.uptime())})}catch(error){res.status(503).json({status:'degraded',checks,checkedAt:new Date().toISOString(),error:'Database connectivity check failed.'})}});
app.get('/api/admin/analytics',admin,async(req,res)=>{const p=await pool.query('select count(*)::int count from progress');const u=await pool.query('select count(distinct user_id)::int count from progress');res.json({progressCount:p.rows[0].count,activeViewers:u.rows[0].count});});
app.get('/api/admin/analytics/series',admin,async(req,res)=>{const requested=Number.parseInt(req.query.days,10)||30;const days=Math.max(7,Math.min(90,requested));const{rows}=await pool.query("select d.day::date as date,(select count(*)::int from progress p where p.updated_at>=d.day and p.updated_at<d.day+interval '1 day') as views,(select count(*)::int from users u where u.created_at>=d.day and u.created_at<d.day+interval '1 day') as signups from generate_series(current_date-($1::int-1)*interval '1 day',current_date,interval '1 day') d(day) order by d.day",[days]);const top=await pool.query("select a.id,a.title,a.poster_url,count(p.episode_id)::int streams from progress p join episodes e on e.id=p.episode_id join anime a on a.id=e.anime_id group by a.id order by streams desc limit 5");res.set('Cache-Control','no-store');res.json({days,series:rows,topStreamed:top.rows})});
app.patch('/api/admin/users/:id/ban',admin,async(req,res)=>{const banned=!!req.body.banned;const{rows}=await pool.query("update users set is_banned=$1 where id=$2 and role='user' returning id,email,is_banned",[banned,req.params.id]);if(!rows[0])return res.sendStatus(404);res.json(rows[0])});
app.patch('/api/admin/anime/bulk',admin,async(req,res)=>{const ids=[...new Set((Array.isArray(req.body.ids)?req.body.ids:[]).map(Number))];if(!ids.length||ids.length>500||ids.some(id=>!Number.isInteger(id)||id<1))return res.status(400).json({error:'Select 1–500 valid anime IDs'});if(req.body.action==='publish'||req.body.action==='draft'){const published=req.body.action==='publish';const{rows}=await pool.query('update anime set is_published=$1 where id=any($2::int[]) returning id,is_published',[published,ids]);return res.json({count:rows.length,anime:rows})}if(req.body.action==='delete'){if(req.staffRole==='editor'||req.staffPermissions.canDelete===false)return res.status(403).json({error:'Delete permission required'});const{rows}=await pool.query('delete from anime where id=any($1::int[]) returning id',[ids]);return res.json({count:rows.length})}return res.status(400).json({error:'Invalid bulk action'})});
app.get('/api/admin/schedule',admin,async(req,res)=>{const{rows}=await pool.query("select id,title,year,status,type,created_at from anime order by case status when 'on-air' then 1 when 'ongoing' then 2 when 'upcoming' then 3 else 4 end,created_at desc");res.json(rows)});
app.get('/api/admin/episodes',admin,async(req,res)=>{const{rows}=await pool.query('select e.*,a.title anime_title from episodes e join anime a on a.id=e.anime_id order by a.title,e.season_number,e.episode_number');res.json(rows)});
app.post('/api/admin/episodes/bulk',admin,async(req,res)=>{const x=req.body,animeId=Number(x.animeId),season=Math.max(1,Number(x.seasonNumber)||1),start=Math.max(1,Number(x.startEpisode)||1),count=Number(x.count);if(!Number.isInteger(animeId)||!Number.isInteger(count)||count<1||count>100)return res.status(400).json({error:'Choose an anime and 1–100 episodes'});const template=String(x.videoUrlTemplate||'').trim();if(!template||!/^https?:\/\//i.test(template.replace('{n}',String(start))))return res.status(400).json({error:'Enter a valid video URL template; use {n} for the episode number'});const check=await pool.query('select id from anime where id=$1',[animeId]);if(!check.rowCount)return res.status(404).json({error:'Anime not found'});const client=await pool.connect();try{await client.query('BEGIN');const created=[];for(let i=0;i<count;i++){const n=start+i,url=template.replaceAll('{n}',String(n)),thumb=String(x.thumbnailUrlTemplate||'').replaceAll('{n}',String(n));const{rows}=await client.query('insert into episodes(anime_id,season_number,episode_number,title,video_url,thumbnail_url,is_exclusive,is_published) values($1,$2,$3,$4,$5,$6,$7,$8) returning *',[animeId,season,n,String(x.titlePrefix||'Episode')+' '+n,'__PDI_CUSTOM__:'+url,thumb,!!x.isExclusive,x.isPublished!==false]);created.push(rows[0])}await client.query('COMMIT');res.status(201).json({count:created.length,episodes:created})}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}});
app.post('/api/admin/episodes',admin,async(req,res)=>{const x=req.body;const{rows}=await pool.query('insert into episodes(anime_id,season_number,episode_number,title,video_url,thumbnail_url,is_exclusive,is_published) values($1,$2,$3,$4,$5,$6,$7,$8) returning *',[x.animeId,x.seasonNumber||1,x.episodeNumber,x.title||'',x.videoUrl,x.thumbnailUrl||'',!!x.isExclusive,x.isPublished!==false]);res.status(201).json(rows[0])});
app.put('/api/admin/episodes/:id',admin,async(req,res)=>{const x=req.body;const{rows}=await pool.query('update episodes set anime_id=$1,season_number=$2,episode_number=$3,title=$4,video_url=$5,thumbnail_url=$6,is_exclusive=$7,is_published=$8 where id=$9 returning *',[x.animeId,x.seasonNumber||1,x.episodeNumber,x.title||'',x.videoUrl,x.thumbnailUrl||'',!!x.isExclusive,x.isPublished!==false,req.params.id]);if(!rows[0])return res.sendStatus(404);res.json(rows[0])});
app.delete('/api/admin/episodes/:id',admin,async(req,res)=>{await pool.query('delete from episodes where id=$1',[req.params.id]);res.sendStatus(204)});
app.get('/api/watchlist',auth,async(req,res)=>{const{rows}=await pool.query('select a.* from watchlist w join anime a on a.id=w.anime_id where w.user_id=$1 order by a.title',[req.user.id]);res.json(rows)});
app.post('/api/watchlist/:animeId',auth,async(req,res)=>{await pool.query('insert into watchlist(user_id,anime_id) values($1,$2) on conflict do nothing',[req.user.id,req.params.animeId]);res.sendStatus(204)});
app.delete('/api/watchlist/:animeId',auth,async(req,res)=>{await pool.query('delete from watchlist where user_id=$1 and anime_id=$2',[req.user.id,req.params.animeId]);res.sendStatus(204)});
app.get('/api/progress',auth,async(req,res)=>{const{rows}=await pool.query('select * from progress where user_id=$1',[req.user.id]);res.json(rows)});
app.put('/api/progress/:episodeId',auth,async(req,res)=>{const seconds=Math.max(0,Number(req.body.seconds)||0);const{rows}=await pool.query('insert into progress(user_id,episode_id,seconds) values($1,$2,$3) on conflict(user_id,episode_id) do update set seconds=$3,updated_at=now() returning *',[req.user.id,req.params.episodeId,seconds]);res.json(rows[0])});
app.use((err, req, res, next) => {
  if (res.headersSent) return next(err);
  if (err?.message === 'Origin not allowed by CORS') return res.status(403).json({error:'Origin not allowed'});
  if (err instanceof SyntaxError && err.status === 400 && 'body' in err) return res.status(400).json({error:'Invalid JSON body'});
  console.error('Unhandled request error', { path: req.path, method: req.method, message: err?.message || 'Unknown error' });
  return res.status(500).json({error:'Internal server error'});
});
init().then(()=>app.listen(process.env.PORT||3000,'0.0.0.0')).catch(e=>{console.error('Startup failed',e);process.exit(1)});
